name: PHP Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check PHP syntax
        run: find . -name "*.php" -print0 | xargs -0 -n1 php -l
